services:
  marten:
    image: postgres:17.0
    env_file:
      - ".env"
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - marten-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.0-management
    env_file:
      - ".env"
    environment:
      RABBITMQ_DEFAULT_USER: "${USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${PASSWORD}"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 10

  svc-identifications:
    build:
      context: .
      dockerfile: Identifications/Dockerfile
    env_file:
      - ".env"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "80"
      ConnectionStrings__marten: "Host=marten;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ConnectionStrings__rabbitmq: "amqp://${USERNAME}:${PASSWORD}@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
      marten:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - app-network

  svc-queries:
    build:
      context: .
      dockerfile: Queries/Dockerfile
    env_file:
      - ".env"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "80"
      ConnectionStrings__marten: "Host=marten;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD}"
      ConnectionStrings__rabbitmq: "amqp://${USERNAME}:${PASSWORD}@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
      marten:
        condition: service_started
    ports:
      - "81:80"
    networks:
      - app-network

volumes:
  marten-data:

networks:
  app-network:
    driver: bridge